# Generated by Django 2.0.3 on 2018-03-27 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
