# Generated by Django 2.0.3 on 2018-03-30 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180330_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='loai',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
