# Generated by Django 2.0.3 on 2018-03-30 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_loai_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='loai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Loai'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
