# Generated by Django 2.0.3 on 2018-03-30 23:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_auto_20180331_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietThanhToan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('sdt', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Số điện thoại không thích hợp.(Chỉ gồm 9-13 ký tự số)', regex='^\\+?1?\\d{9,13}$')])),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='chitietthanhtoan',
            name='thanhtoan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.ThanhToan'),
        ),
    ]
