# Generated by Django 2.0.3 on 2018-03-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180331_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='products/noimg.png', upload_to='products/'),
        ),
    ]
